//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: fulfillment/v1/compute_instance_type.proto

//go:build protoopaque

package fulfillmentv1

import (
	v1 "github.com/innabox/cloudkit-operator/internal/api/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the overall state of a compute instance.
type ComputeInstanceState int32

const (
	// Unspecified indicates that the state is unknown.
	ComputeInstanceState_COMPUTE_INSTANCE_STATE_UNSPECIFIED ComputeInstanceState = 0
	// Indicates that the compute instance is starting.
	ComputeInstanceState_COMPUTE_INSTANCE_STATE_STARTING ComputeInstanceState = 1
	// Indicates that the compute instance is running.
	ComputeInstanceState_COMPUTE_INSTANCE_STATE_RUNNING ComputeInstanceState = 2
	// Indicates that the compute instance is unusable.
	ComputeInstanceState_COMPUTE_INSTANCE_STATE_FAILED ComputeInstanceState = 3
	// Indicates that the compute instance is being deleted.
	ComputeInstanceState_COMPUTE_INSTANCE_STATE_DELETING ComputeInstanceState = 4
)

// Enum value maps for ComputeInstanceState.
var (
	ComputeInstanceState_name = map[int32]string{
		0: "COMPUTE_INSTANCE_STATE_UNSPECIFIED",
		1: "COMPUTE_INSTANCE_STATE_STARTING",
		2: "COMPUTE_INSTANCE_STATE_RUNNING",
		3: "COMPUTE_INSTANCE_STATE_FAILED",
		4: "COMPUTE_INSTANCE_STATE_DELETING",
	}
	ComputeInstanceState_value = map[string]int32{
		"COMPUTE_INSTANCE_STATE_UNSPECIFIED": 0,
		"COMPUTE_INSTANCE_STATE_STARTING":    1,
		"COMPUTE_INSTANCE_STATE_RUNNING":     2,
		"COMPUTE_INSTANCE_STATE_FAILED":      3,
		"COMPUTE_INSTANCE_STATE_DELETING":    4,
	}
)

func (x ComputeInstanceState) Enum() *ComputeInstanceState {
	p := new(ComputeInstanceState)
	*p = x
	return p
}

func (x ComputeInstanceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComputeInstanceState) Descriptor() protoreflect.EnumDescriptor {
	return file_fulfillment_v1_compute_instance_type_proto_enumTypes[0].Descriptor()
}

func (ComputeInstanceState) Type() protoreflect.EnumType {
	return &file_fulfillment_v1_compute_instance_type_proto_enumTypes[0]
}

func (x ComputeInstanceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Types of conditions used to describe the status of compute instance.
type ComputeInstanceConditionType int32

const (
	// Unspecified indicates that the condition is unknown.
	//
	// This will never be appear in the `spec.conditions` field of a compute instance.
	ComputeInstanceConditionType_COMPUTE_INSTANCE_CONDITION_TYPE_UNSPECIFIED ComputeInstanceConditionType = 0
	// Indicates that the compute instance isn't completely ready yet.
	//
	// Currently there are no `reason` values defined.
	ComputeInstanceConditionType_COMPUTE_INSTANCE_CONDITION_TYPE_PROGRESSING ComputeInstanceConditionType = 1
	// Indicates that the compute instance is available.
	//
	// Currently there are no `reason` values defined.
	ComputeInstanceConditionType_COMPUTE_INSTANCE_CONDITION_TYPE_AVAILABLE ComputeInstanceConditionType = 2
	// Indicates that the compute instance is unusable.
	//
	// Currently there are no `reason` values defined.
	ComputeInstanceConditionType_COMPUTE_INSTANCE_CONDITION_TYPE_FAILED ComputeInstanceConditionType = 3
	// Indicates that the compute instance is degraded.
	ComputeInstanceConditionType_COMPUTE_INSTANCE_CONDITION_TYPE_DEGRADED ComputeInstanceConditionType = 4
	// Indicates that a restart is in progress.
	//
	// When `status` is `TRUE`, it means a restart is currently in progress.
	//
	// Possible `reason` values:
	// - `RestartRequested`: A restart has been requested via `spec.restart_requested_at`.
	// - `RestartInProgress`: The restart has been initiated.
	//
	// When `status` is `FALSE`, no restart is currently in progress.
	ComputeInstanceConditionType_COMPUTE_INSTANCE_CONDITION_TYPE_RESTART_IN_PROGRESS ComputeInstanceConditionType = 5
	// Indicates that a restart request has failed.
	//
	// When `status` is `TRUE`, it means the restart could not be executed.
	// The `message` field will contain details about the failure.
	// If the issue persists, please contact your administrator.
	//
	// When `status` is `FALSE`, there is no restart failure.
	ComputeInstanceConditionType_COMPUTE_INSTANCE_CONDITION_TYPE_RESTART_FAILED ComputeInstanceConditionType = 6
)

// Enum value maps for ComputeInstanceConditionType.
var (
	ComputeInstanceConditionType_name = map[int32]string{
		0: "COMPUTE_INSTANCE_CONDITION_TYPE_UNSPECIFIED",
		1: "COMPUTE_INSTANCE_CONDITION_TYPE_PROGRESSING",
		2: "COMPUTE_INSTANCE_CONDITION_TYPE_AVAILABLE",
		3: "COMPUTE_INSTANCE_CONDITION_TYPE_FAILED",
		4: "COMPUTE_INSTANCE_CONDITION_TYPE_DEGRADED",
		5: "COMPUTE_INSTANCE_CONDITION_TYPE_RESTART_IN_PROGRESS",
		6: "COMPUTE_INSTANCE_CONDITION_TYPE_RESTART_FAILED",
	}
	ComputeInstanceConditionType_value = map[string]int32{
		"COMPUTE_INSTANCE_CONDITION_TYPE_UNSPECIFIED":         0,
		"COMPUTE_INSTANCE_CONDITION_TYPE_PROGRESSING":         1,
		"COMPUTE_INSTANCE_CONDITION_TYPE_AVAILABLE":           2,
		"COMPUTE_INSTANCE_CONDITION_TYPE_FAILED":              3,
		"COMPUTE_INSTANCE_CONDITION_TYPE_DEGRADED":            4,
		"COMPUTE_INSTANCE_CONDITION_TYPE_RESTART_IN_PROGRESS": 5,
		"COMPUTE_INSTANCE_CONDITION_TYPE_RESTART_FAILED":      6,
	}
)

func (x ComputeInstanceConditionType) Enum() *ComputeInstanceConditionType {
	p := new(ComputeInstanceConditionType)
	*p = x
	return p
}

func (x ComputeInstanceConditionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComputeInstanceConditionType) Descriptor() protoreflect.EnumDescriptor {
	return file_fulfillment_v1_compute_instance_type_proto_enumTypes[1].Descriptor()
}

func (ComputeInstanceConditionType) Type() protoreflect.EnumType {
	return &file_fulfillment_v1_compute_instance_type_proto_enumTypes[1]
}

func (x ComputeInstanceConditionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Contains the details of the compute instance.
//
// The `spec` contains the desired details, and may be modified by the user. The `status` contains the current status of
// the compute instance, is provided by the system and can't be modified by the user.
type ComputeInstance struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id       string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Metadata *v1.Metadata           `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_Spec     *ComputeInstanceSpec   `protobuf:"bytes,3,opt,name=spec,proto3"`
	xxx_hidden_Status   *ComputeInstanceStatus `protobuf:"bytes,4,opt,name=status,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ComputeInstance) Reset() {
	*x = ComputeInstance{}
	mi := &file_fulfillment_v1_compute_instance_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstance) ProtoMessage() {}

func (x *ComputeInstance) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_compute_instance_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstance) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *ComputeInstance) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ComputeInstance) GetSpec() *ComputeInstanceSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *ComputeInstance) GetStatus() *ComputeInstanceStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *ComputeInstance) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *ComputeInstance) SetMetadata(v *v1.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ComputeInstance) SetSpec(v *ComputeInstanceSpec) {
	x.xxx_hidden_Spec = v
}

func (x *ComputeInstance) SetStatus(v *ComputeInstanceStatus) {
	x.xxx_hidden_Status = v
}

func (x *ComputeInstance) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ComputeInstance) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *ComputeInstance) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *ComputeInstance) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *ComputeInstance) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *ComputeInstance) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type ComputeInstance_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the compute instance.
	Id       string
	Metadata *v1.Metadata
	Spec     *ComputeInstanceSpec
	Status   *ComputeInstanceStatus
}

func (b0 ComputeInstance_builder) Build() *ComputeInstance {
	m0 := &ComputeInstance{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

// The spec contains the details of a compute instance as desired by the user.
type ComputeInstanceSpec struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Template           string                 `protobuf:"bytes,1,opt,name=template,proto3"`
	xxx_hidden_TemplateParameters map[string]*anypb.Any  `protobuf:"bytes,2,rep,name=template_parameters,json=templateParameters,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_RestartRequestedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=restart_requested_at,json=restartRequestedAt,proto3,oneof"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ComputeInstanceSpec) Reset() {
	*x = ComputeInstanceSpec{}
	mi := &file_fulfillment_v1_compute_instance_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceSpec) ProtoMessage() {}

func (x *ComputeInstanceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_compute_instance_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceSpec) GetTemplate() string {
	if x != nil {
		return x.xxx_hidden_Template
	}
	return ""
}

func (x *ComputeInstanceSpec) GetTemplateParameters() map[string]*anypb.Any {
	if x != nil {
		return x.xxx_hidden_TemplateParameters
	}
	return nil
}

func (x *ComputeInstanceSpec) GetRestartRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_RestartRequestedAt
	}
	return nil
}

func (x *ComputeInstanceSpec) SetTemplate(v string) {
	x.xxx_hidden_Template = v
}

func (x *ComputeInstanceSpec) SetTemplateParameters(v map[string]*anypb.Any) {
	x.xxx_hidden_TemplateParameters = v
}

func (x *ComputeInstanceSpec) SetRestartRequestedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_RestartRequestedAt = v
}

func (x *ComputeInstanceSpec) HasRestartRequestedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RestartRequestedAt != nil
}

func (x *ComputeInstanceSpec) ClearRestartRequestedAt() {
	x.xxx_hidden_RestartRequestedAt = nil
}

type ComputeInstanceSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Reference to the compute instance template.
	//
	// This is mandatory, and must be the value of the `id` field of one of the compute instance templates.
	//
	// This can't be modified after the compute instance is created.
	Template string
	// Values of the template parameters.
	//
	// When using the HTTP+JSON version of the API the values must be represented as documented in the (ProtoJSON format
	// document)[https://protobuf.dev/programming-guides/json]. For example, if the template has a `cpu_count`
	// parameter of integer type, the complete compute instance should be represented like this:
	//
	// ```json
	//
	//	{
	//	  "spec": {
	//	    "template": "123",
	//	    "template_parameters": {
	//	      "cpu_count": {
	//	        "@type": "type.googleapis.com/google.protobuf.Int32Value",
	//	        "value": 4
	//	      }
	//	    }
	//	  }
	//	}
	//
	// ```
	//
	// The possible values of the `@type` are the same as those used by the `type_url` field of the `Any` type:
	//
	// | Type                           | Value                                             |
	// |--------------------------------|---------------------------------------------------|
	// | Boolean                        | `type.googleapis.com/google.protobuf.BoolValue`   |
	// | Integer number, 32 bits        | `type.googleapis.com/google.protobuf.Int32Value`  |
	// | Integer number, 64 bits        | `type.googleapis.com/google.protobuf.Int64Value`  |
	// | Floating point number, 32 bits | `type.googleapis.com/google.protobuf.FloatValue`  |
	// | Floating point number, 64 bits | `type.googleapis.com/google.protobuf.DoubleValue` |
	// | String                         | `type.googleapis.com/google.protobuf.StringValue` |
	// | Timestamp                      | `type.googleapis.com/google.protobuf.Timestamp`   |
	// | Duration                       | `type.googleapis.com/google.protobuf.Duration`    |
	// | Array of bytes                 | `type.googleapis.com/google.protobuf.BytesValue`  |
	// | Any JSON value                 | `type.googleapis.com/google.protobuf.Value`       |
	//
	// These parameters can't be modified after the compute instance is created.
	TemplateParameters map[string]*anypb.Any
	// RestartRequestedAt is a timestamp signal to request a ComputeInstance restart.
	//
	// Set this field to the current time (usually NOW) to request a restart.
	// The controller will execute the restart if this timestamp is greater than
	// `status.last_restarted_at`.
	//
	// This is a declarative signal mechanism - the timestamp is a monotonically
	// increasing value to detect new restart requests, not a scheduled time.
	// Typically set to the current time for immediate restarts.
	//
	// External schedulers can set this field on a schedule to implement
	// scheduled maintenance windows if needed.
	//
	// Example (when converted to JSON):
	//
	//	{
	//	  "spec": {
	//	    "template": "123",
	//	    "restart_requested_at": "2026-01-20T14:30:00Z"
	//	  }
	//	}
	RestartRequestedAt *timestamppb.Timestamp
}

func (b0 ComputeInstanceSpec_builder) Build() *ComputeInstanceSpec {
	m0 := &ComputeInstanceSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Template = b.Template
	x.xxx_hidden_TemplateParameters = b.TemplateParameters
	x.xxx_hidden_RestartRequestedAt = b.RestartRequestedAt
	return m0
}

// The status contains the details of the compute instance provided by the system.
type ComputeInstanceStatus struct {
	state                      protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_State           ComputeInstanceState         `protobuf:"varint,1,opt,name=state,proto3,enum=fulfillment.v1.ComputeInstanceState"`
	xxx_hidden_Conditions      *[]*ComputeInstanceCondition `protobuf:"bytes,2,rep,name=conditions,proto3"`
	xxx_hidden_IpAddress       string                       `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3"`
	xxx_hidden_LastRestartedAt *timestamppb.Timestamp       `protobuf:"bytes,4,opt,name=last_restarted_at,json=lastRestartedAt,proto3,oneof"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ComputeInstanceStatus) Reset() {
	*x = ComputeInstanceStatus{}
	mi := &file_fulfillment_v1_compute_instance_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceStatus) ProtoMessage() {}

func (x *ComputeInstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_compute_instance_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceStatus) GetState() ComputeInstanceState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return ComputeInstanceState_COMPUTE_INSTANCE_STATE_UNSPECIFIED
}

func (x *ComputeInstanceStatus) GetConditions() []*ComputeInstanceCondition {
	if x != nil {
		if x.xxx_hidden_Conditions != nil {
			return *x.xxx_hidden_Conditions
		}
	}
	return nil
}

func (x *ComputeInstanceStatus) GetIpAddress() string {
	if x != nil {
		return x.xxx_hidden_IpAddress
	}
	return ""
}

func (x *ComputeInstanceStatus) GetLastRestartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastRestartedAt
	}
	return nil
}

func (x *ComputeInstanceStatus) SetState(v ComputeInstanceState) {
	x.xxx_hidden_State = v
}

func (x *ComputeInstanceStatus) SetConditions(v []*ComputeInstanceCondition) {
	x.xxx_hidden_Conditions = &v
}

func (x *ComputeInstanceStatus) SetIpAddress(v string) {
	x.xxx_hidden_IpAddress = v
}

func (x *ComputeInstanceStatus) SetLastRestartedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastRestartedAt = v
}

func (x *ComputeInstanceStatus) HasLastRestartedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastRestartedAt != nil
}

func (x *ComputeInstanceStatus) ClearLastRestartedAt() {
	x.xxx_hidden_LastRestartedAt = nil
}

type ComputeInstanceStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Indicates the overall state of the compute instance.
	State ComputeInstanceState
	// Contains a list of conditions that describe in detail the status of the compute instance.
	//
	// For example, a running compute instance could be represented like this (when converted to JSON):
	//
	//	{
	//	  "id": "123",
	//	  "spec": {
	//	  },
	//	  "status": {
	//	    "state": "COMPUTE_INSTANCE_STATE_RUNNING",
	//	    "conditions": [
	//	      {
	//	        "type": "COMPUTE_INSTANCE_CONDITION_TYPE_AVAILABLE",
	//	        "status": "CONDITION_STATUS_TRUE",
	//	        "last_transition_time": "2025-03-12 20:15:59+00:00",
	//	        "message": "The compute instance is available",
	//	      }
	//	    ]
	//	  }
	//	}
	//
	// In this example the `AVAILABLE` condition is true. That tells us that the compute instance is available via the IP address
	// provided in the `status.ip_address` field.
	//
	// Note that in this example, to make it shorter, only one condition appears. In general all the conditions (except
	// `UNSPECIFIED`) will appear exactly once.
	//
	// Check the documentation of the values of the `ComputeInstanceConditionType` enumerated type to see possible conditions and
	// reasons.
	Conditions []*ComputeInstanceCondition
	// IP address of the compute instance.
	//
	// This will be empty if the compute instance isn't running.
	IpAddress string
	// LastRestartedAt records when the last restart was initiated by the controller.
	//
	// This is set to `spec.restart_requested_at` when the controller processes a restart request.
	// It will be empty if no restart has been performed yet.
	//
	// Example (when converted to JSON):
	//
	//	{
	//	  "status": {
	//	    "state": "COMPUTE_INSTANCE_STATE_RUNNING",
	//	    "last_restarted_at": "2026-01-20T14:30:00Z"
	//	  }
	//	}
	LastRestartedAt *timestamppb.Timestamp
}

func (b0 ComputeInstanceStatus_builder) Build() *ComputeInstanceStatus {
	m0 := &ComputeInstanceStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Conditions = &b.Conditions
	x.xxx_hidden_IpAddress = b.IpAddress
	x.xxx_hidden_LastRestartedAt = b.LastRestartedAt
	return m0
}

// Contains the details of a condition that describes the status of a compute instance.
type ComputeInstanceCondition struct {
	state                         protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Type               ComputeInstanceConditionType `protobuf:"varint,1,opt,name=type,proto3,enum=fulfillment.v1.ComputeInstanceConditionType"`
	xxx_hidden_Status             v1.ConditionStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=shared.v1.ConditionStatus"`
	xxx_hidden_LastTransitionTime *timestamppb.Timestamp       `protobuf:"bytes,3,opt,name=last_transition_time,json=lastTransitionTime,proto3"`
	xxx_hidden_Reason             *string                      `protobuf:"bytes,4,opt,name=reason,proto3,oneof"`
	xxx_hidden_Message            *string                      `protobuf:"bytes,5,opt,name=message,proto3,oneof"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ComputeInstanceCondition) Reset() {
	*x = ComputeInstanceCondition{}
	mi := &file_fulfillment_v1_compute_instance_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceCondition) ProtoMessage() {}

func (x *ComputeInstanceCondition) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_compute_instance_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceCondition) GetType() ComputeInstanceConditionType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ComputeInstanceConditionType_COMPUTE_INSTANCE_CONDITION_TYPE_UNSPECIFIED
}

func (x *ComputeInstanceCondition) GetStatus() v1.ConditionStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return v1.ConditionStatus(0)
}

func (x *ComputeInstanceCondition) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastTransitionTime
	}
	return nil
}

func (x *ComputeInstanceCondition) GetReason() string {
	if x != nil {
		if x.xxx_hidden_Reason != nil {
			return *x.xxx_hidden_Reason
		}
		return ""
	}
	return ""
}

func (x *ComputeInstanceCondition) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ComputeInstanceCondition) SetType(v ComputeInstanceConditionType) {
	x.xxx_hidden_Type = v
}

func (x *ComputeInstanceCondition) SetStatus(v v1.ConditionStatus) {
	x.xxx_hidden_Status = v
}

func (x *ComputeInstanceCondition) SetLastTransitionTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastTransitionTime = v
}

func (x *ComputeInstanceCondition) SetReason(v string) {
	x.xxx_hidden_Reason = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *ComputeInstanceCondition) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *ComputeInstanceCondition) HasLastTransitionTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastTransitionTime != nil
}

func (x *ComputeInstanceCondition) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ComputeInstanceCondition) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ComputeInstanceCondition) ClearLastTransitionTime() {
	x.xxx_hidden_LastTransitionTime = nil
}

func (x *ComputeInstanceCondition) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Reason = nil
}

func (x *ComputeInstanceCondition) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Message = nil
}

type ComputeInstanceCondition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Indicates the type of condition.
	Type ComputeInstanceConditionType
	// Indicates the status of the condition.
	Status v1.ConditionStatus
	// This time is the last time that the condition was updated.
	LastTransitionTime *timestamppb.Timestamp
	// Contains a the reason of the condition in a format suitable for use by programs.
	//
	// The possible values will be documented in the object that contains the condition.
	Reason *string
	// Contains a text giving more details of the condition.
	//
	// This will usually be progress reports, or error messages, and are intended for use by humans, to debug problems.
	Message *string
}

func (b0 ComputeInstanceCondition_builder) Build() *ComputeInstanceCondition {
	m0 := &ComputeInstanceCondition{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_LastTransitionTime = b.LastTransitionTime
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Reason = b.Reason
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

var File_fulfillment_v1_compute_instance_type_proto protoreflect.FileDescriptor

var file_fulfillment_v1_compute_instance_type_proto_rawDesc = string([]byte{
	0x0a, 0x2a, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x66, 0x75,
	0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca,
	0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x3d, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x66,
	0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xe8, 0x02, 0x0a, 0x13,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12,
	0x6c, 0x0a, 0x13, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x66,
	0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x70, 0x65,
	0x63, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x12, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x51, 0x0a,
	0x14, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x12, 0x72, 0x65, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01,
	0x1a, 0x5b, 0x0a, 0x17, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x17, 0x0a,
	0x15, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x22, 0x9f, 0x02, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x70, 0x75,
	0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x3a, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x24, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x48, 0x0a, 0x0a,
	0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x4b, 0x0a, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x65,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x0f,
	0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x88,
	0x01, 0x01, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x22, 0xb1, 0x02, 0x0a, 0x18, 0x43, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x4c, 0x0a, 0x14, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0xcf, 0x01, 0x0a,
	0x14, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x22, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45,
	0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x23, 0x0a,
	0x1f, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43,
	0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e,
	0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x55, 0x4e,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x21, 0x0a, 0x1d, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54,
	0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x23, 0x0a, 0x1f, 0x43, 0x4f, 0x4d,
	0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x2a, 0xf6,
	0x02, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x2f, 0x0a, 0x2b, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41,
	0x4e, 0x43, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x2f, 0x0a, 0x2b, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54,
	0x41, 0x4e, 0x43, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10,
	0x01, 0x12, 0x2d, 0x0a, 0x29, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53,
	0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02,
	0x12, 0x2a, 0x0a, 0x26, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54,
	0x41, 0x4e, 0x43, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x2c, 0x0a, 0x28,
	0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45,
	0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x44, 0x45, 0x47, 0x52, 0x41, 0x44, 0x45, 0x44, 0x10, 0x04, 0x12, 0x37, 0x0a, 0x33, 0x43, 0x4f,
	0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x43,
	0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53,
	0x53, 0x10, 0x05, 0x12, 0x32, 0x0a, 0x2e, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49,
	0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x46,
	0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x06, 0x42, 0xd7, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e,
	0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x18,
	0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x6e, 0x61, 0x62, 0x6f, 0x78, 0x2f, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x6b, 0x69, 0x74, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x75,
	0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x75, 0x6c,
	0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x46, 0x58, 0x58,
	0xaa, 0x02, 0x0e, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x0e, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x5c,
	0x56, 0x31, 0xe2, 0x02, 0x1a, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x0f, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_fulfillment_v1_compute_instance_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fulfillment_v1_compute_instance_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fulfillment_v1_compute_instance_type_proto_goTypes = []any{
	(ComputeInstanceState)(0),         // 0: fulfillment.v1.ComputeInstanceState
	(ComputeInstanceConditionType)(0), // 1: fulfillment.v1.ComputeInstanceConditionType
	(*ComputeInstance)(nil),           // 2: fulfillment.v1.ComputeInstance
	(*ComputeInstanceSpec)(nil),       // 3: fulfillment.v1.ComputeInstanceSpec
	(*ComputeInstanceStatus)(nil),     // 4: fulfillment.v1.ComputeInstanceStatus
	(*ComputeInstanceCondition)(nil),  // 5: fulfillment.v1.ComputeInstanceCondition
	nil,                               // 6: fulfillment.v1.ComputeInstanceSpec.TemplateParametersEntry
	(*v1.Metadata)(nil),               // 7: shared.v1.Metadata
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
	(v1.ConditionStatus)(0),           // 9: shared.v1.ConditionStatus
	(*anypb.Any)(nil),                 // 10: google.protobuf.Any
}
var file_fulfillment_v1_compute_instance_type_proto_depIdxs = []int32{
	7,  // 0: fulfillment.v1.ComputeInstance.metadata:type_name -> shared.v1.Metadata
	3,  // 1: fulfillment.v1.ComputeInstance.spec:type_name -> fulfillment.v1.ComputeInstanceSpec
	4,  // 2: fulfillment.v1.ComputeInstance.status:type_name -> fulfillment.v1.ComputeInstanceStatus
	6,  // 3: fulfillment.v1.ComputeInstanceSpec.template_parameters:type_name -> fulfillment.v1.ComputeInstanceSpec.TemplateParametersEntry
	8,  // 4: fulfillment.v1.ComputeInstanceSpec.restart_requested_at:type_name -> google.protobuf.Timestamp
	0,  // 5: fulfillment.v1.ComputeInstanceStatus.state:type_name -> fulfillment.v1.ComputeInstanceState
	5,  // 6: fulfillment.v1.ComputeInstanceStatus.conditions:type_name -> fulfillment.v1.ComputeInstanceCondition
	8,  // 7: fulfillment.v1.ComputeInstanceStatus.last_restarted_at:type_name -> google.protobuf.Timestamp
	1,  // 8: fulfillment.v1.ComputeInstanceCondition.type:type_name -> fulfillment.v1.ComputeInstanceConditionType
	9,  // 9: fulfillment.v1.ComputeInstanceCondition.status:type_name -> shared.v1.ConditionStatus
	8,  // 10: fulfillment.v1.ComputeInstanceCondition.last_transition_time:type_name -> google.protobuf.Timestamp
	10, // 11: fulfillment.v1.ComputeInstanceSpec.TemplateParametersEntry.value:type_name -> google.protobuf.Any
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_fulfillment_v1_compute_instance_type_proto_init() }
func file_fulfillment_v1_compute_instance_type_proto_init() {
	if File_fulfillment_v1_compute_instance_type_proto != nil {
		return
	}
	file_fulfillment_v1_compute_instance_type_proto_msgTypes[1].OneofWrappers = []any{}
	file_fulfillment_v1_compute_instance_type_proto_msgTypes[2].OneofWrappers = []any{}
	file_fulfillment_v1_compute_instance_type_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fulfillment_v1_compute_instance_type_proto_rawDesc), len(file_fulfillment_v1_compute_instance_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fulfillment_v1_compute_instance_type_proto_goTypes,
		DependencyIndexes: file_fulfillment_v1_compute_instance_type_proto_depIdxs,
		EnumInfos:         file_fulfillment_v1_compute_instance_type_proto_enumTypes,
		MessageInfos:      file_fulfillment_v1_compute_instance_type_proto_msgTypes,
	}.Build()
	File_fulfillment_v1_compute_instance_type_proto = out.File
	file_fulfillment_v1_compute_instance_type_proto_goTypes = nil
	file_fulfillment_v1_compute_instance_type_proto_depIdxs = nil
}
