//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: fulfillment/v1/compute_instance_template_type.proto

//go:build !protoopaque

package fulfillmentv1

import (
	v1 "github.com/osac/osac-operator/internal/api/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A compute instance template defines a type of compute instance that can be created by the user. Note that the user doesn't create these
// templates: the system provides a collection of them, and the user chooses one.
type ComputeInstanceTemplate struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the template.
	Id       string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata *v1.Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Human friendly short description of the template, only a few words, suitable for displaying in one single line on a
	// UI or CLI.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Human friendly long description of the template, using Markdown format.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Definitions of the parameters that can be used to customize the template.
	//
	// Note that these are only the *definitions* of the parameters, not the actual values. The actual values are in the
	// `spec.template_parameters` field of the compute instance.
	Parameters    []*ComputeInstanceTemplateParameterDefinition `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeInstanceTemplate) Reset() {
	*x = ComputeInstanceTemplate{}
	mi := &file_fulfillment_v1_compute_instance_template_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceTemplate) ProtoMessage() {}

func (x *ComputeInstanceTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_compute_instance_template_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComputeInstanceTemplate) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ComputeInstanceTemplate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ComputeInstanceTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ComputeInstanceTemplate) GetParameters() []*ComputeInstanceTemplateParameterDefinition {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ComputeInstanceTemplate) SetId(v string) {
	x.Id = v
}

func (x *ComputeInstanceTemplate) SetMetadata(v *v1.Metadata) {
	x.Metadata = v
}

func (x *ComputeInstanceTemplate) SetTitle(v string) {
	x.Title = v
}

func (x *ComputeInstanceTemplate) SetDescription(v string) {
	x.Description = v
}

func (x *ComputeInstanceTemplate) SetParameters(v []*ComputeInstanceTemplateParameterDefinition) {
	x.Parameters = v
}

func (x *ComputeInstanceTemplate) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *ComputeInstanceTemplate) ClearMetadata() {
	x.Metadata = nil
}

type ComputeInstanceTemplate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the template.
	Id       string
	Metadata *v1.Metadata
	// Human friendly short description of the template, only a few words, suitable for displaying in one single line on a
	// UI or CLI.
	Title string
	// Human friendly long description of the template, using Markdown format.
	Description string
	// Definitions of the parameters that can be used to customize the template.
	//
	// Note that these are only the *definitions* of the parameters, not the actual values. The actual values are in the
	// `spec.template_parameters` field of the compute instance.
	Parameters []*ComputeInstanceTemplateParameterDefinition
}

func (b0 ComputeInstanceTemplate_builder) Build() *ComputeInstanceTemplate {
	m0 := &ComputeInstanceTemplate{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Title = b.Title
	x.Description = b.Description
	x.Parameters = b.Parameters
	return m0
}

// Contains type and documentation of a template parameter.
type ComputeInstanceTemplateParameterDefinition struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Name of the parameter.
	//
	// This is the name that should be used in the `template_parameters` field of the compute instance to assign a value to the
	// parameter.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human friendly short description of the parameter, only a few words, suitable for displaying in one single line on
	// a UI or CLI.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Human friendly description of the parameter, using Markdown format.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Indicates if this parameter is required or optional.
	//
	// Values for required parameters must be included when creating the compute instance, otherwise it will be rejected.
	//
	// Note that there may be other dependencies between parameters which may cause a compute instance to be rejected. For example,
	// the allowed values of a parameter may depend on the value of another parameter. That kind of information will be in
	// the `description` field.
	Required bool `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	// Type of the parameter.
	//
	// The possible values are the same as those used by the `type_url` field of the `Any` type:
	//
	// | Type                           | Value                                             |
	// |--------------------------------|---------------------------------------------------|
	// | Boolean                        | `type.googleapis.com/google.protobuf.BoolValue`   |
	// | Integer number, 32 bits        | `type.googleapis.com/google.protobuf.Int32Value`  |
	// | Integer number, 64 bits        | `type.googleapis.com/google.protobuf.Int64Value`  |
	// | Floating point number, 32 bits | `type.googleapis.com/google.protobuf.FloatValue`  |
	// | Floating point number, 64 bits | `type.googleapis.com/google.protobuf.DoubleValue` |
	// | String                         | `type.googleapis.com/google.protobuf.StringValue` |
	// | Timestamp                      | `type.googleapis.com/google.protobuf.Timestamp`   |
	// | Duration                       | `type.googleapis.com/google.protobuf.Duration`    |
	// | Array of bytes                 | `type.googleapis.com/google.protobuf.BytesValue`  |
	// | Any JSON value                 | `type.googleapis.com/google.protobuf.Value`       |
	//
	// When using the HTTP+JSON version of the API the value provided in the `template_parameters` field of the compute instance
	// must be represented as documented in the (ProtoJSON format document)[https://protobuf.dev/programming-guides/json].
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// Default value for optional parameters.
	Default       *anypb.Any `protobuf:"bytes,6,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeInstanceTemplateParameterDefinition) Reset() {
	*x = ComputeInstanceTemplateParameterDefinition{}
	mi := &file_fulfillment_v1_compute_instance_template_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceTemplateParameterDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceTemplateParameterDefinition) ProtoMessage() {}

func (x *ComputeInstanceTemplateParameterDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_fulfillment_v1_compute_instance_template_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceTemplateParameterDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComputeInstanceTemplateParameterDefinition) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ComputeInstanceTemplateParameterDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ComputeInstanceTemplateParameterDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ComputeInstanceTemplateParameterDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ComputeInstanceTemplateParameterDefinition) GetDefault() *anypb.Any {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *ComputeInstanceTemplateParameterDefinition) SetName(v string) {
	x.Name = v
}

func (x *ComputeInstanceTemplateParameterDefinition) SetTitle(v string) {
	x.Title = v
}

func (x *ComputeInstanceTemplateParameterDefinition) SetDescription(v string) {
	x.Description = v
}

func (x *ComputeInstanceTemplateParameterDefinition) SetRequired(v bool) {
	x.Required = v
}

func (x *ComputeInstanceTemplateParameterDefinition) SetType(v string) {
	x.Type = v
}

func (x *ComputeInstanceTemplateParameterDefinition) SetDefault(v *anypb.Any) {
	x.Default = v
}

func (x *ComputeInstanceTemplateParameterDefinition) HasDefault() bool {
	if x == nil {
		return false
	}
	return x.Default != nil
}

func (x *ComputeInstanceTemplateParameterDefinition) ClearDefault() {
	x.Default = nil
}

type ComputeInstanceTemplateParameterDefinition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the parameter.
	//
	// This is the name that should be used in the `template_parameters` field of the compute instance to assign a value to the
	// parameter.
	Name string
	// Human friendly short description of the parameter, only a few words, suitable for displaying in one single line on
	// a UI or CLI.
	Title string
	// Human friendly description of the parameter, using Markdown format.
	Description string
	// Indicates if this parameter is required or optional.
	//
	// Values for required parameters must be included when creating the compute instance, otherwise it will be rejected.
	//
	// Note that there may be other dependencies between parameters which may cause a compute instance to be rejected. For example,
	// the allowed values of a parameter may depend on the value of another parameter. That kind of information will be in
	// the `description` field.
	Required bool
	// Type of the parameter.
	//
	// The possible values are the same as those used by the `type_url` field of the `Any` type:
	//
	// | Type                           | Value                                             |
	// |--------------------------------|---------------------------------------------------|
	// | Boolean                        | `type.googleapis.com/google.protobuf.BoolValue`   |
	// | Integer number, 32 bits        | `type.googleapis.com/google.protobuf.Int32Value`  |
	// | Integer number, 64 bits        | `type.googleapis.com/google.protobuf.Int64Value`  |
	// | Floating point number, 32 bits | `type.googleapis.com/google.protobuf.FloatValue`  |
	// | Floating point number, 64 bits | `type.googleapis.com/google.protobuf.DoubleValue` |
	// | String                         | `type.googleapis.com/google.protobuf.StringValue` |
	// | Timestamp                      | `type.googleapis.com/google.protobuf.Timestamp`   |
	// | Duration                       | `type.googleapis.com/google.protobuf.Duration`    |
	// | Array of bytes                 | `type.googleapis.com/google.protobuf.BytesValue`  |
	// | Any JSON value                 | `type.googleapis.com/google.protobuf.Value`       |
	//
	// When using the HTTP+JSON version of the API the value provided in the `template_parameters` field of the compute instance
	// must be represented as documented in the (ProtoJSON format document)[https://protobuf.dev/programming-guides/json].
	Type string
	// Default value for optional parameters.
	Default *anypb.Any
}

func (b0 ComputeInstanceTemplateParameterDefinition_builder) Build() *ComputeInstanceTemplateParameterDefinition {
	m0 := &ComputeInstanceTemplateParameterDefinition{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.Title = b.Title
	x.Description = b.Description
	x.Required = b.Required
	x.Type = b.Type
	x.Default = b.Default
	return m0
}

var File_fulfillment_v1_compute_instance_template_type_proto protoreflect.FileDescriptor

var file_fulfillment_v1_compute_instance_template_type_proto_rawDesc = string([]byte{
	0x0a, 0x33, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xee, 0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5a, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x22, 0xd8, 0x01, 0x0a, 0x2a, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x42, 0xd8, 0x01, 0x0a, 0x12,
	0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x42, 0x20, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76,
	0x31, 0x3b, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x46, 0x58, 0x58, 0xaa, 0x02, 0x0e, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0e, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c,
	0x6d, 0x65, 0x6e, 0x74, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1a, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0f, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_fulfillment_v1_compute_instance_template_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fulfillment_v1_compute_instance_template_type_proto_goTypes = []any{
	(*ComputeInstanceTemplate)(nil),                    // 0: fulfillment.v1.ComputeInstanceTemplate
	(*ComputeInstanceTemplateParameterDefinition)(nil), // 1: fulfillment.v1.ComputeInstanceTemplateParameterDefinition
	(*v1.Metadata)(nil),                                // 2: shared.v1.Metadata
	(*anypb.Any)(nil),                                  // 3: google.protobuf.Any
}
var file_fulfillment_v1_compute_instance_template_type_proto_depIdxs = []int32{
	2, // 0: fulfillment.v1.ComputeInstanceTemplate.metadata:type_name -> shared.v1.Metadata
	1, // 1: fulfillment.v1.ComputeInstanceTemplate.parameters:type_name -> fulfillment.v1.ComputeInstanceTemplateParameterDefinition
	3, // 2: fulfillment.v1.ComputeInstanceTemplateParameterDefinition.default:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fulfillment_v1_compute_instance_template_type_proto_init() }
func file_fulfillment_v1_compute_instance_template_type_proto_init() {
	if File_fulfillment_v1_compute_instance_template_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fulfillment_v1_compute_instance_template_type_proto_rawDesc), len(file_fulfillment_v1_compute_instance_template_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fulfillment_v1_compute_instance_template_type_proto_goTypes,
		DependencyIndexes: file_fulfillment_v1_compute_instance_template_type_proto_depIdxs,
		MessageInfos:      file_fulfillment_v1_compute_instance_template_type_proto_msgTypes,
	}.Build()
	File_fulfillment_v1_compute_instance_template_type_proto = out.File
	file_fulfillment_v1_compute_instance_template_type_proto_goTypes = nil
	file_fulfillment_v1_compute_instance_template_type_proto_depIdxs = nil
}
