{{- if .Values.hubAccess.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-hub-access
  labels:
    {{- include "osac-operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
rules:
- apiGroups:
  - osac.openshift.io
  resources:
  - baremetalinstances
  - clusterorders
  - computeinstances
  - externalipattachments
  - externalippools
  - externalips
  - natgateways
  - publicipattachments
  - publicippools
  - publicips
  - securitygroups
  - subnets
  - tenants
  - virtualnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osac.openshift.io
  resources:
  - baremetalinstances/status
  - clusterorders/status
  - computeinstances/status
  - externalipattachments/status
  - externalippools/status
  - externalips/status
  - natgateways/status
  - publicipattachments/status
  - publicippools/status
  - publicips/status
  - securitygroups/status
  - subnets/status
  - tenants/status
  - virtualnetworks/status
  verbs:
  - get
- apiGroups:
  - console.osac.openshift.io
  resources:
  - computeinstances/console
  - computeinstances/vnc
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
{{- end }}
