apiVersion: osac.openshift.io/v1alpha1
kind: BareMetalPool
metadata:
  labels:
    app.kubernetes.io/name: osac-operator
    app.kubernetes.io/managed-by: kustomize
  name: baremetalpool-sample
spec:
  # TODO(user): Add fields here
