//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/identity_provider_type.proto

//go:build protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdentityProviderPhase represents the current phase of an identity provider.
type IdentityProviderPhase int32

const (
	// IDENTITY_PROVIDER_PHASE_UNSPECIFIED is the default value.
	IdentityProviderPhase_IDENTITY_PROVIDER_PHASE_UNSPECIFIED IdentityProviderPhase = 0
	// IDENTITY_PROVIDER_PHASE_READY indicates the IdP is ready and operational.
	IdentityProviderPhase_IDENTITY_PROVIDER_PHASE_READY IdentityProviderPhase = 1
	// IDENTITY_PROVIDER_PHASE_ERROR indicates the IdP is in an error state.
	IdentityProviderPhase_IDENTITY_PROVIDER_PHASE_ERROR IdentityProviderPhase = 2
	// IDENTITY_PROVIDER_PHASE_UNKNOWN indicates the IdP state is unknown.
	IdentityProviderPhase_IDENTITY_PROVIDER_PHASE_UNKNOWN IdentityProviderPhase = 3
)

// Enum value maps for IdentityProviderPhase.
var (
	IdentityProviderPhase_name = map[int32]string{
		0: "IDENTITY_PROVIDER_PHASE_UNSPECIFIED",
		1: "IDENTITY_PROVIDER_PHASE_READY",
		2: "IDENTITY_PROVIDER_PHASE_ERROR",
		3: "IDENTITY_PROVIDER_PHASE_UNKNOWN",
	}
	IdentityProviderPhase_value = map[string]int32{
		"IDENTITY_PROVIDER_PHASE_UNSPECIFIED": 0,
		"IDENTITY_PROVIDER_PHASE_READY":       1,
		"IDENTITY_PROVIDER_PHASE_ERROR":       2,
		"IDENTITY_PROVIDER_PHASE_UNKNOWN":     3,
	}
)

func (x IdentityProviderPhase) Enum() *IdentityProviderPhase {
	p := new(IdentityProviderPhase)
	*p = x
	return p
}

func (x IdentityProviderPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityProviderPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_identity_provider_type_proto_enumTypes[0].Descriptor()
}

func (IdentityProviderPhase) Type() protoreflect.EnumType {
	return &file_osac_private_v1_identity_provider_type_proto_enumTypes[0]
}

func (x IdentityProviderPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// IdentityProviderHealthStatus represents the health status of an identity provider.
type IdentityProviderHealthStatus int32

const (
	// IDENTITY_PROVIDER_HEALTH_STATUS_UNSPECIFIED is the default value.
	IdentityProviderHealthStatus_IDENTITY_PROVIDER_HEALTH_STATUS_UNSPECIFIED IdentityProviderHealthStatus = 0
	// IDENTITY_PROVIDER_HEALTH_STATUS_HEALTHY indicates the IdP is healthy.
	IdentityProviderHealthStatus_IDENTITY_PROVIDER_HEALTH_STATUS_HEALTHY IdentityProviderHealthStatus = 1
	// IDENTITY_PROVIDER_HEALTH_STATUS_UNHEALTHY indicates the IdP is unhealthy.
	IdentityProviderHealthStatus_IDENTITY_PROVIDER_HEALTH_STATUS_UNHEALTHY IdentityProviderHealthStatus = 2
	// IDENTITY_PROVIDER_HEALTH_STATUS_UNKNOWN indicates the health status is unknown.
	IdentityProviderHealthStatus_IDENTITY_PROVIDER_HEALTH_STATUS_UNKNOWN IdentityProviderHealthStatus = 3
)

// Enum value maps for IdentityProviderHealthStatus.
var (
	IdentityProviderHealthStatus_name = map[int32]string{
		0: "IDENTITY_PROVIDER_HEALTH_STATUS_UNSPECIFIED",
		1: "IDENTITY_PROVIDER_HEALTH_STATUS_HEALTHY",
		2: "IDENTITY_PROVIDER_HEALTH_STATUS_UNHEALTHY",
		3: "IDENTITY_PROVIDER_HEALTH_STATUS_UNKNOWN",
	}
	IdentityProviderHealthStatus_value = map[string]int32{
		"IDENTITY_PROVIDER_HEALTH_STATUS_UNSPECIFIED": 0,
		"IDENTITY_PROVIDER_HEALTH_STATUS_HEALTHY":     1,
		"IDENTITY_PROVIDER_HEALTH_STATUS_UNHEALTHY":   2,
		"IDENTITY_PROVIDER_HEALTH_STATUS_UNKNOWN":     3,
	}
)

func (x IdentityProviderHealthStatus) Enum() *IdentityProviderHealthStatus {
	p := new(IdentityProviderHealthStatus)
	*p = x
	return p
}

func (x IdentityProviderHealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityProviderHealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_identity_provider_type_proto_enumTypes[1].Descriptor()
}

func (IdentityProviderHealthStatus) Type() protoreflect.EnumType {
	return &file_osac_private_v1_identity_provider_type_proto_enumTypes[1]
}

func (x IdentityProviderHealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// IdentityProvider represents an external identity provider configuration.
// Identity providers enable users to authenticate using their existing corporate credentials
// (LDAP, Active Directory, OIDC, SAML, etc.).
type IdentityProvider struct {
	state               protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Id       string                  `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Metadata *Metadata               `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_Spec     *IdentityProviderSpec   `protobuf:"bytes,3,opt,name=spec,proto3"`
	xxx_hidden_Status   *IdentityProviderStatus `protobuf:"bytes,4,opt,name=status,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IdentityProvider) Reset() {
	*x = IdentityProvider{}
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProvider) ProtoMessage() {}

func (x *IdentityProvider) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IdentityProvider) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *IdentityProvider) GetMetadata() *Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *IdentityProvider) GetSpec() *IdentityProviderSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *IdentityProvider) GetStatus() *IdentityProviderStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *IdentityProvider) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *IdentityProvider) SetMetadata(v *Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *IdentityProvider) SetSpec(v *IdentityProviderSpec) {
	x.xxx_hidden_Spec = v
}

func (x *IdentityProvider) SetStatus(v *IdentityProviderStatus) {
	x.xxx_hidden_Status = v
}

func (x *IdentityProvider) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *IdentityProvider) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *IdentityProvider) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *IdentityProvider) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *IdentityProvider) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *IdentityProvider) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type IdentityProvider_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier for this IdP. Immutable after creation.
	Id string
	// Metadata contains common object metadata.
	Metadata *Metadata
	// Spec is the desired state of the identity provider.
	Spec *IdentityProviderSpec
	// Status is the observed state of the identity provider.
	Status *IdentityProviderStatus
}

func (b0 IdentityProvider_builder) Build() *IdentityProvider {
	m0 := &IdentityProvider{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

// IdentityProviderSpec represents the desired state of an identity provider.
type IdentityProviderSpec struct {
	state                  protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Title       string                        `protobuf:"bytes,1,opt,name=title,proto3"`
	xxx_hidden_Description *string                       `protobuf:"bytes,2,opt,name=description,proto3,oneof"`
	xxx_hidden_Enabled     bool                          `protobuf:"varint,3,opt,name=enabled,proto3"`
	xxx_hidden_Config      isIdentityProviderSpec_Config `protobuf_oneof:"config"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IdentityProviderSpec) Reset() {
	*x = IdentityProviderSpec{}
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProviderSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProviderSpec) ProtoMessage() {}

func (x *IdentityProviderSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IdentityProviderSpec) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *IdentityProviderSpec) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *IdentityProviderSpec) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *IdentityProviderSpec) GetOidc() *OidcConfig {
	if x != nil {
		if x, ok := x.xxx_hidden_Config.(*identityProviderSpec_Oidc); ok {
			return x.Oidc
		}
	}
	return nil
}

func (x *IdentityProviderSpec) GetLdap() *LdapConfig {
	if x != nil {
		if x, ok := x.xxx_hidden_Config.(*identityProviderSpec_Ldap); ok {
			return x.Ldap
		}
	}
	return nil
}

func (x *IdentityProviderSpec) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *IdentityProviderSpec) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *IdentityProviderSpec) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
}

func (x *IdentityProviderSpec) SetOidc(v *OidcConfig) {
	if v == nil {
		x.xxx_hidden_Config = nil
		return
	}
	x.xxx_hidden_Config = &identityProviderSpec_Oidc{v}
}

func (x *IdentityProviderSpec) SetLdap(v *LdapConfig) {
	if v == nil {
		x.xxx_hidden_Config = nil
		return
	}
	x.xxx_hidden_Config = &identityProviderSpec_Ldap{v}
}

func (x *IdentityProviderSpec) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *IdentityProviderSpec) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *IdentityProviderSpec) HasOidc() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Config.(*identityProviderSpec_Oidc)
	return ok
}

func (x *IdentityProviderSpec) HasLdap() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Config.(*identityProviderSpec_Ldap)
	return ok
}

func (x *IdentityProviderSpec) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

func (x *IdentityProviderSpec) ClearConfig() {
	x.xxx_hidden_Config = nil
}

func (x *IdentityProviderSpec) ClearOidc() {
	if _, ok := x.xxx_hidden_Config.(*identityProviderSpec_Oidc); ok {
		x.xxx_hidden_Config = nil
	}
}

func (x *IdentityProviderSpec) ClearLdap() {
	if _, ok := x.xxx_hidden_Config.(*identityProviderSpec_Ldap); ok {
		x.xxx_hidden_Config = nil
	}
}

const IdentityProviderSpec_Config_not_set_case case_IdentityProviderSpec_Config = 0
const IdentityProviderSpec_Oidc_case case_IdentityProviderSpec_Config = 4
const IdentityProviderSpec_Ldap_case case_IdentityProviderSpec_Config = 5

func (x *IdentityProviderSpec) WhichConfig() case_IdentityProviderSpec_Config {
	if x == nil {
		return IdentityProviderSpec_Config_not_set_case
	}
	switch x.xxx_hidden_Config.(type) {
	case *identityProviderSpec_Oidc:
		return IdentityProviderSpec_Oidc_case
	case *identityProviderSpec_Ldap:
		return IdentityProviderSpec_Ldap_case
	default:
		return IdentityProviderSpec_Config_not_set_case
	}
}

type IdentityProviderSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Human-friendly short title for this IdP, suitable for displaying in a single line.
	// Example: "Corporate LDAP" or "GitHub SSO"
	Title string
	// Human-friendly description explaining the purpose or scope of this IdP.
	// Example: "Primary LDAP server for employee authentication"
	Description *string
	// Enabled indicates whether this IdP should be active and available for authentication.
	Enabled bool
	// Provider-specific configuration settings.
	// The type of identity provider is determined by which config field is set.

	// Fields of oneof xxx_hidden_Config:
	// Configuration for OpenID Connect providers.
	Oidc *OidcConfig
	// Configuration for LDAP providers.
	Ldap *LdapConfig
	// -- end of xxx_hidden_Config
}

func (b0 IdentityProviderSpec_builder) Build() *IdentityProviderSpec {
	m0 := &IdentityProviderSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Description = b.Description
	}
	x.xxx_hidden_Enabled = b.Enabled
	if b.Oidc != nil {
		x.xxx_hidden_Config = &identityProviderSpec_Oidc{b.Oidc}
	}
	if b.Ldap != nil {
		x.xxx_hidden_Config = &identityProviderSpec_Ldap{b.Ldap}
	}
	return m0
}

type case_IdentityProviderSpec_Config protoreflect.FieldNumber

func (x case_IdentityProviderSpec_Config) String() string {
	md := file_osac_private_v1_identity_provider_type_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isIdentityProviderSpec_Config interface {
	isIdentityProviderSpec_Config()
}

type identityProviderSpec_Oidc struct {
	// Configuration for OpenID Connect providers.
	Oidc *OidcConfig `protobuf:"bytes,4,opt,name=oidc,proto3,oneof"`
}

type identityProviderSpec_Ldap struct {
	// Configuration for LDAP providers.
	Ldap *LdapConfig `protobuf:"bytes,5,opt,name=ldap,proto3,oneof"`
}

func (*identityProviderSpec_Oidc) isIdentityProviderSpec_Config() {}

func (*identityProviderSpec_Ldap) isIdentityProviderSpec_Config() {}

// OidcConfig contains configuration for OpenID Connect identity providers.
type OidcConfig struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AuthorizationUrl  string                 `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3"`
	xxx_hidden_TokenUrl          string                 `protobuf:"bytes,2,opt,name=token_url,json=tokenUrl,proto3"`
	xxx_hidden_ClientId          string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3"`
	xxx_hidden_ClientSecret      string                 `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret,proto3"`
	xxx_hidden_Issuer            string                 `protobuf:"bytes,5,opt,name=issuer,proto3"`
	xxx_hidden_DefaultScopes     *string                `protobuf:"bytes,6,opt,name=default_scopes,json=defaultScopes,proto3,oneof"`
	xxx_hidden_UserInfoUrl       *string                `protobuf:"bytes,7,opt,name=user_info_url,json=userInfoUrl,proto3,oneof"`
	xxx_hidden_JwksUrl           *string                `protobuf:"bytes,8,opt,name=jwks_url,json=jwksUrl,proto3,oneof"`
	xxx_hidden_ValidateSignature bool                   `protobuf:"varint,9,opt,name=validate_signature,json=validateSignature,proto3,oneof"`
	xxx_hidden_LogoutUrl         *string                `protobuf:"bytes,10,opt,name=logout_url,json=logoutUrl,proto3,oneof"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *OidcConfig) Reset() {
	*x = OidcConfig{}
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OidcConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OidcConfig) ProtoMessage() {}

func (x *OidcConfig) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OidcConfig) GetAuthorizationUrl() string {
	if x != nil {
		return x.xxx_hidden_AuthorizationUrl
	}
	return ""
}

func (x *OidcConfig) GetTokenUrl() string {
	if x != nil {
		return x.xxx_hidden_TokenUrl
	}
	return ""
}

func (x *OidcConfig) GetClientId() string {
	if x != nil {
		return x.xxx_hidden_ClientId
	}
	return ""
}

func (x *OidcConfig) GetClientSecret() string {
	if x != nil {
		return x.xxx_hidden_ClientSecret
	}
	return ""
}

func (x *OidcConfig) GetIssuer() string {
	if x != nil {
		return x.xxx_hidden_Issuer
	}
	return ""
}

func (x *OidcConfig) GetDefaultScopes() string {
	if x != nil {
		if x.xxx_hidden_DefaultScopes != nil {
			return *x.xxx_hidden_DefaultScopes
		}
		return ""
	}
	return ""
}

func (x *OidcConfig) GetUserInfoUrl() string {
	if x != nil {
		if x.xxx_hidden_UserInfoUrl != nil {
			return *x.xxx_hidden_UserInfoUrl
		}
		return ""
	}
	return ""
}

func (x *OidcConfig) GetJwksUrl() string {
	if x != nil {
		if x.xxx_hidden_JwksUrl != nil {
			return *x.xxx_hidden_JwksUrl
		}
		return ""
	}
	return ""
}

func (x *OidcConfig) GetValidateSignature() bool {
	if x != nil {
		return x.xxx_hidden_ValidateSignature
	}
	return false
}

func (x *OidcConfig) GetLogoutUrl() string {
	if x != nil {
		if x.xxx_hidden_LogoutUrl != nil {
			return *x.xxx_hidden_LogoutUrl
		}
		return ""
	}
	return ""
}

func (x *OidcConfig) SetAuthorizationUrl(v string) {
	x.xxx_hidden_AuthorizationUrl = v
}

func (x *OidcConfig) SetTokenUrl(v string) {
	x.xxx_hidden_TokenUrl = v
}

func (x *OidcConfig) SetClientId(v string) {
	x.xxx_hidden_ClientId = v
}

func (x *OidcConfig) SetClientSecret(v string) {
	x.xxx_hidden_ClientSecret = v
}

func (x *OidcConfig) SetIssuer(v string) {
	x.xxx_hidden_Issuer = v
}

func (x *OidcConfig) SetDefaultScopes(v string) {
	x.xxx_hidden_DefaultScopes = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *OidcConfig) SetUserInfoUrl(v string) {
	x.xxx_hidden_UserInfoUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 10)
}

func (x *OidcConfig) SetJwksUrl(v string) {
	x.xxx_hidden_JwksUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 10)
}

func (x *OidcConfig) SetValidateSignature(v bool) {
	x.xxx_hidden_ValidateSignature = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 10)
}

func (x *OidcConfig) SetLogoutUrl(v string) {
	x.xxx_hidden_LogoutUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *OidcConfig) HasDefaultScopes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *OidcConfig) HasUserInfoUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *OidcConfig) HasJwksUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *OidcConfig) HasValidateSignature() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *OidcConfig) HasLogoutUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *OidcConfig) ClearDefaultScopes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_DefaultScopes = nil
}

func (x *OidcConfig) ClearUserInfoUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_UserInfoUrl = nil
}

func (x *OidcConfig) ClearJwksUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_JwksUrl = nil
}

func (x *OidcConfig) ClearValidateSignature() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_ValidateSignature = false
}

func (x *OidcConfig) ClearLogoutUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_LogoutUrl = nil
}

type OidcConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Authorization endpoint URL where users are redirected to authenticate.
	// Example: "https://accounts.google.com/o/oauth2/v2/auth"
	AuthorizationUrl string
	// Token endpoint URL used to exchange authorization codes for access tokens.
	// Example: "https://oauth2.googleapis.com/token"
	TokenUrl string
	// Client identifier issued by the OIDC provider.
	// This is a public identifier for the application.
	ClientId string
	// Client secret for authenticating with the OIDC provider.
	// This field is write-only and will never be returned in API responses.
	ClientSecret string
	// Issuer URL that identifies the OIDC provider.
	// Used for validating ID tokens. Must match the 'iss' claim in tokens.
	// Example: "https://accounts.google.com"
	Issuer string
	// Space-separated list of OAuth scopes to request.
	// Common scopes: "openid profile email"
	// Default: "openid profile email"
	DefaultScopes *string
	// UserInfo endpoint URL for retrieving user profile information.
	// If not specified, user info will be extracted from the ID token.
	// Example: "https://openidconnect.googleapis.com/v1/userinfo"
	UserInfoUrl *string
	// JSON Web Key Set (JWKS) URL for obtaining public keys to verify ID token signatures.
	// If not specified, the provider's discovery endpoint will be used.
	// Example: "https://www.googleapis.com/oauth2/v3/certs"
	JwksUrl *string
	// Whether to validate ID token signatures using JWKS.
	// Default: true
	ValidateSignature *bool
	// Logout URL where users are redirected after logging out.
	// Example: "https://accounts.google.com/logout"
	LogoutUrl *string
}

func (b0 OidcConfig_builder) Build() *OidcConfig {
	m0 := &OidcConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AuthorizationUrl = b.AuthorizationUrl
	x.xxx_hidden_TokenUrl = b.TokenUrl
	x.xxx_hidden_ClientId = b.ClientId
	x.xxx_hidden_ClientSecret = b.ClientSecret
	x.xxx_hidden_Issuer = b.Issuer
	if b.DefaultScopes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_DefaultScopes = b.DefaultScopes
	}
	if b.UserInfoUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 10)
		x.xxx_hidden_UserInfoUrl = b.UserInfoUrl
	}
	if b.JwksUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 10)
		x.xxx_hidden_JwksUrl = b.JwksUrl
	}
	if b.ValidateSignature != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 10)
		x.xxx_hidden_ValidateSignature = *b.ValidateSignature
	}
	if b.LogoutUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_LogoutUrl = b.LogoutUrl
	}
	return m0
}

// LdapConfig contains configuration for LDAP identity providers.
type LdapConfig struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ConnectionUrl         string                 `protobuf:"bytes,1,opt,name=connection_url,json=connectionUrl,proto3"`
	xxx_hidden_BindDn                string                 `protobuf:"bytes,2,opt,name=bind_dn,json=bindDn,proto3"`
	xxx_hidden_BindCredential        string                 `protobuf:"bytes,3,opt,name=bind_credential,json=bindCredential,proto3"`
	xxx_hidden_UsersDn               string                 `protobuf:"bytes,4,opt,name=users_dn,json=usersDn,proto3"`
	xxx_hidden_UsernameLdapAttribute *string                `protobuf:"bytes,5,opt,name=username_ldap_attribute,json=usernameLdapAttribute,proto3,oneof"`
	xxx_hidden_RdnLdapAttribute      *string                `protobuf:"bytes,6,opt,name=rdn_ldap_attribute,json=rdnLdapAttribute,proto3,oneof"`
	xxx_hidden_UuidLdapAttribute     *string                `protobuf:"bytes,7,opt,name=uuid_ldap_attribute,json=uuidLdapAttribute,proto3,oneof"`
	xxx_hidden_UserObjectClasses     *string                `protobuf:"bytes,8,opt,name=user_object_classes,json=userObjectClasses,proto3,oneof"`
	xxx_hidden_AuthType              *string                `protobuf:"bytes,9,opt,name=auth_type,json=authType,proto3,oneof"`
	xxx_hidden_Vendor                *string                `protobuf:"bytes,10,opt,name=vendor,proto3,oneof"`
	xxx_hidden_UseTruststoreSpi      bool                   `protobuf:"varint,11,opt,name=use_truststore_spi,json=useTruststoreSpi,proto3,oneof"`
	xxx_hidden_Pagination            bool                   `protobuf:"varint,12,opt,name=pagination,proto3,oneof"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *LdapConfig) Reset() {
	*x = LdapConfig{}
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LdapConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LdapConfig) ProtoMessage() {}

func (x *LdapConfig) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LdapConfig) GetConnectionUrl() string {
	if x != nil {
		return x.xxx_hidden_ConnectionUrl
	}
	return ""
}

func (x *LdapConfig) GetBindDn() string {
	if x != nil {
		return x.xxx_hidden_BindDn
	}
	return ""
}

func (x *LdapConfig) GetBindCredential() string {
	if x != nil {
		return x.xxx_hidden_BindCredential
	}
	return ""
}

func (x *LdapConfig) GetUsersDn() string {
	if x != nil {
		return x.xxx_hidden_UsersDn
	}
	return ""
}

func (x *LdapConfig) GetUsernameLdapAttribute() string {
	if x != nil {
		if x.xxx_hidden_UsernameLdapAttribute != nil {
			return *x.xxx_hidden_UsernameLdapAttribute
		}
		return ""
	}
	return ""
}

func (x *LdapConfig) GetRdnLdapAttribute() string {
	if x != nil {
		if x.xxx_hidden_RdnLdapAttribute != nil {
			return *x.xxx_hidden_RdnLdapAttribute
		}
		return ""
	}
	return ""
}

func (x *LdapConfig) GetUuidLdapAttribute() string {
	if x != nil {
		if x.xxx_hidden_UuidLdapAttribute != nil {
			return *x.xxx_hidden_UuidLdapAttribute
		}
		return ""
	}
	return ""
}

func (x *LdapConfig) GetUserObjectClasses() string {
	if x != nil {
		if x.xxx_hidden_UserObjectClasses != nil {
			return *x.xxx_hidden_UserObjectClasses
		}
		return ""
	}
	return ""
}

func (x *LdapConfig) GetAuthType() string {
	if x != nil {
		if x.xxx_hidden_AuthType != nil {
			return *x.xxx_hidden_AuthType
		}
		return ""
	}
	return ""
}

func (x *LdapConfig) GetVendor() string {
	if x != nil {
		if x.xxx_hidden_Vendor != nil {
			return *x.xxx_hidden_Vendor
		}
		return ""
	}
	return ""
}

func (x *LdapConfig) GetUseTruststoreSpi() bool {
	if x != nil {
		return x.xxx_hidden_UseTruststoreSpi
	}
	return false
}

func (x *LdapConfig) GetPagination() bool {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return false
}

func (x *LdapConfig) SetConnectionUrl(v string) {
	x.xxx_hidden_ConnectionUrl = v
}

func (x *LdapConfig) SetBindDn(v string) {
	x.xxx_hidden_BindDn = v
}

func (x *LdapConfig) SetBindCredential(v string) {
	x.xxx_hidden_BindCredential = v
}

func (x *LdapConfig) SetUsersDn(v string) {
	x.xxx_hidden_UsersDn = v
}

func (x *LdapConfig) SetUsernameLdapAttribute(v string) {
	x.xxx_hidden_UsernameLdapAttribute = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *LdapConfig) SetRdnLdapAttribute(v string) {
	x.xxx_hidden_RdnLdapAttribute = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *LdapConfig) SetUuidLdapAttribute(v string) {
	x.xxx_hidden_UuidLdapAttribute = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 12)
}

func (x *LdapConfig) SetUserObjectClasses(v string) {
	x.xxx_hidden_UserObjectClasses = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *LdapConfig) SetAuthType(v string) {
	x.xxx_hidden_AuthType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 12)
}

func (x *LdapConfig) SetVendor(v string) {
	x.xxx_hidden_Vendor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 12)
}

func (x *LdapConfig) SetUseTruststoreSpi(v bool) {
	x.xxx_hidden_UseTruststoreSpi = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 12)
}

func (x *LdapConfig) SetPagination(v bool) {
	x.xxx_hidden_Pagination = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 12)
}

func (x *LdapConfig) HasUsernameLdapAttribute() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *LdapConfig) HasRdnLdapAttribute() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *LdapConfig) HasUuidLdapAttribute() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *LdapConfig) HasUserObjectClasses() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *LdapConfig) HasAuthType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *LdapConfig) HasVendor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *LdapConfig) HasUseTruststoreSpi() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *LdapConfig) HasPagination() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *LdapConfig) ClearUsernameLdapAttribute() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_UsernameLdapAttribute = nil
}

func (x *LdapConfig) ClearRdnLdapAttribute() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_RdnLdapAttribute = nil
}

func (x *LdapConfig) ClearUuidLdapAttribute() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_UuidLdapAttribute = nil
}

func (x *LdapConfig) ClearUserObjectClasses() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_UserObjectClasses = nil
}

func (x *LdapConfig) ClearAuthType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_AuthType = nil
}

func (x *LdapConfig) ClearVendor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Vendor = nil
}

func (x *LdapConfig) ClearUseTruststoreSpi() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_UseTruststoreSpi = false
}

func (x *LdapConfig) ClearPagination() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_Pagination = false
}

type LdapConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Connection URL for the LDAP server.
	// Supports ldap:// and ldaps:// (SSL/TLS) protocols.
	// Example: "ldap://ldap.example.com:389" or "ldaps://ldap.example.com:636"
	ConnectionUrl string
	// Distinguished Name (DN) of the user to bind as for authenticating to the LDAP server.
	// This user must have permissions to search for users in the directory.
	// Example: "cn=admin,dc=example,dc=com"
	BindDn string
	// Password for the bind DN user.
	// This field is write-only and will never be returned in API responses.
	BindCredential string
	// Base Distinguished Name where user entries are located in the LDAP directory.
	// All user searches will be performed under this DN.
	// Example: "ou=users,dc=example,dc=com"
	UsersDn string
	// LDAP attribute to use as the username for authentication.
	// Common values: "uid", "cn", "sAMAccountName" (Active Directory)
	// Default: "uid"
	UsernameLdapAttribute *string
	// LDAP attribute containing the user's RDN (Relative Distinguished Name).
	// Used to construct the full DN when authenticating users.
	// Common values: "uid", "cn"
	// Default: "uid"
	RdnLdapAttribute *string
	// LDAP attribute containing the user's unique identifier.
	// Maps to the user ID in the application.
	// Common values: "uid", "entryUUID", "objectGUID" (Active Directory)
	// Default: "uid"
	UuidLdapAttribute *string
	// LDAP filter to apply when searching for users.
	// Must return users to be allowed to authenticate.
	// Example: "(objectClass=person)"
	UserObjectClasses *string
	// Authentication type to use when binding.
	// Valid values: "simple" (username/password), "none" (anonymous)
	// Default: "simple"
	AuthType *string
	// LDAP server vendor for vendor-specific optimizations.
	// Valid values: "ad" (Active Directory), "rhds" (Red Hat Directory Server),
	// "tivoli" (IBM Tivoli), "edirectory" (Novell eDirectory), "other"
	// Default: "other"
	Vendor *string
	// Whether to use STARTTLS to upgrade the connection to TLS.
	// Only applicable for ldap:// URLs (not ldaps://).
	// Default: false
	UseTruststoreSpi *bool
	// Whether to enable pagination when searching for users.
	// Useful for large directories to avoid timeouts.
	// Default: true
	Pagination *bool
}

func (b0 LdapConfig_builder) Build() *LdapConfig {
	m0 := &LdapConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ConnectionUrl = b.ConnectionUrl
	x.xxx_hidden_BindDn = b.BindDn
	x.xxx_hidden_BindCredential = b.BindCredential
	x.xxx_hidden_UsersDn = b.UsersDn
	if b.UsernameLdapAttribute != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_UsernameLdapAttribute = b.UsernameLdapAttribute
	}
	if b.RdnLdapAttribute != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_RdnLdapAttribute = b.RdnLdapAttribute
	}
	if b.UuidLdapAttribute != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 12)
		x.xxx_hidden_UuidLdapAttribute = b.UuidLdapAttribute
	}
	if b.UserObjectClasses != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_UserObjectClasses = b.UserObjectClasses
	}
	if b.AuthType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 12)
		x.xxx_hidden_AuthType = b.AuthType
	}
	if b.Vendor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 12)
		x.xxx_hidden_Vendor = b.Vendor
	}
	if b.UseTruststoreSpi != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 12)
		x.xxx_hidden_UseTruststoreSpi = *b.UseTruststoreSpi
	}
	if b.Pagination != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 12)
		x.xxx_hidden_Pagination = *b.Pagination
	}
	return m0
}

// IdentityProviderStatus represents the operational status of an identity provider.
type IdentityProviderStatus struct {
	state                 protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Phase      IdentityProviderPhase         `protobuf:"varint,1,opt,name=phase,proto3,enum=osac.private.v1.IdentityProviderPhase"`
	xxx_hidden_Message    string                        `protobuf:"bytes,2,opt,name=message,proto3"`
	xxx_hidden_Conditions *[]*IdentityProviderCondition `protobuf:"bytes,3,rep,name=conditions,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *IdentityProviderStatus) Reset() {
	*x = IdentityProviderStatus{}
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProviderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProviderStatus) ProtoMessage() {}

func (x *IdentityProviderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IdentityProviderStatus) GetPhase() IdentityProviderPhase {
	if x != nil {
		return x.xxx_hidden_Phase
	}
	return IdentityProviderPhase_IDENTITY_PROVIDER_PHASE_UNSPECIFIED
}

func (x *IdentityProviderStatus) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *IdentityProviderStatus) GetConditions() []*IdentityProviderCondition {
	if x != nil {
		if x.xxx_hidden_Conditions != nil {
			return *x.xxx_hidden_Conditions
		}
	}
	return nil
}

func (x *IdentityProviderStatus) SetPhase(v IdentityProviderPhase) {
	x.xxx_hidden_Phase = v
}

func (x *IdentityProviderStatus) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

func (x *IdentityProviderStatus) SetConditions(v []*IdentityProviderCondition) {
	x.xxx_hidden_Conditions = &v
}

type IdentityProviderStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Phase represents the current phase of the identity provider.
	Phase IdentityProviderPhase
	// Message provides additional context about the current status.
	Message string
	// Conditions represent specific aspects of the identity provider's status.
	Conditions []*IdentityProviderCondition
}

func (b0 IdentityProviderStatus_builder) Build() *IdentityProviderStatus {
	m0 := &IdentityProviderStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Phase = b.Phase
	x.xxx_hidden_Message = b.Message
	x.xxx_hidden_Conditions = &b.Conditions
	return m0
}

// IdentityProviderCondition represents a specific condition of the identity provider.
type IdentityProviderCondition struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type               string                 `protobuf:"bytes,1,opt,name=type,proto3"`
	xxx_hidden_Status             ConditionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=osac.private.v1.ConditionStatus"`
	xxx_hidden_Reason             string                 `protobuf:"bytes,3,opt,name=reason,proto3"`
	xxx_hidden_Message            string                 `protobuf:"bytes,4,opt,name=message,proto3"`
	xxx_hidden_LastTransitionTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_transition_time,json=lastTransitionTime,proto3"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *IdentityProviderCondition) Reset() {
	*x = IdentityProviderCondition{}
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProviderCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProviderCondition) ProtoMessage() {}

func (x *IdentityProviderCondition) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IdentityProviderCondition) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *IdentityProviderCondition) GetStatus() ConditionStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ConditionStatus_CONDITION_STATUS_UNSPECIFIED
}

func (x *IdentityProviderCondition) GetReason() string {
	if x != nil {
		return x.xxx_hidden_Reason
	}
	return ""
}

func (x *IdentityProviderCondition) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *IdentityProviderCondition) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastTransitionTime
	}
	return nil
}

func (x *IdentityProviderCondition) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *IdentityProviderCondition) SetStatus(v ConditionStatus) {
	x.xxx_hidden_Status = v
}

func (x *IdentityProviderCondition) SetReason(v string) {
	x.xxx_hidden_Reason = v
}

func (x *IdentityProviderCondition) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

func (x *IdentityProviderCondition) SetLastTransitionTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastTransitionTime = v
}

func (x *IdentityProviderCondition) HasLastTransitionTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastTransitionTime != nil
}

func (x *IdentityProviderCondition) ClearLastTransitionTime() {
	x.xxx_hidden_LastTransitionTime = nil
}

type IdentityProviderCondition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Type of condition. Examples: "Reachable", "Configured", "Authenticated"
	Type string
	// Status of the condition.
	Status ConditionStatus
	// Reason is a brief machine-readable explanation for the condition's status.
	Reason string
	// Message is a human-readable explanation for the condition's status.
	Message string
	// LastTransitionTime is the last time the condition transitioned from one status to another.
	LastTransitionTime *timestamppb.Timestamp
}

func (b0 IdentityProviderCondition_builder) Build() *IdentityProviderCondition {
	m0 := &IdentityProviderCondition{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_Reason = b.Reason
	x.xxx_hidden_Message = b.Message
	x.xxx_hidden_LastTransitionTime = b.LastTransitionTime
	return m0
}

// IdentityProviderHealth represents the health status of an identity provider.
type IdentityProviderHealth struct {
	state                  protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Status      IdentityProviderHealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=osac.private.v1.IdentityProviderHealthStatus"`
	xxx_hidden_Message     *string                      `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
	xxx_hidden_LastChecked *timestamppb.Timestamp       `protobuf:"bytes,3,opt,name=last_checked,json=lastChecked,proto3"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IdentityProviderHealth) Reset() {
	*x = IdentityProviderHealth{}
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityProviderHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityProviderHealth) ProtoMessage() {}

func (x *IdentityProviderHealth) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_identity_provider_type_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IdentityProviderHealth) GetStatus() IdentityProviderHealthStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return IdentityProviderHealthStatus_IDENTITY_PROVIDER_HEALTH_STATUS_UNSPECIFIED
}

func (x *IdentityProviderHealth) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *IdentityProviderHealth) GetLastChecked() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastChecked
	}
	return nil
}

func (x *IdentityProviderHealth) SetStatus(v IdentityProviderHealthStatus) {
	x.xxx_hidden_Status = v
}

func (x *IdentityProviderHealth) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *IdentityProviderHealth) SetLastChecked(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastChecked = v
}

func (x *IdentityProviderHealth) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *IdentityProviderHealth) HasLastChecked() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastChecked != nil
}

func (x *IdentityProviderHealth) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

func (x *IdentityProviderHealth) ClearLastChecked() {
	x.xxx_hidden_LastChecked = nil
}

type IdentityProviderHealth_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Status indicates the overall health status.
	Status IdentityProviderHealthStatus
	// Message provides details about the health status.
	Message *string
	// LastChecked is when the health was last checked.
	LastChecked *timestamppb.Timestamp
}

func (b0 IdentityProviderHealth_builder) Build() *IdentityProviderHealth {
	m0 := &IdentityProviderHealth{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Message = b.Message
	}
	x.xxx_hidden_LastChecked = b.LastChecked
	return m0
}

var File_osac_private_v1_identity_provider_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_identity_provider_type_proto_rawDesc = string([]byte{
	0x0a, 0x2c, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x2b, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f,
	0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a, 0x10, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x39,
	0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xed, 0x01, 0x0a, 0x14, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x53,
	0x70, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x31, 0x0a, 0x04, 0x6f, 0x69,
	0x64, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x69, 0x64, 0x63, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x69, 0x64, 0x63, 0x12, 0x31, 0x0a,
	0x04, 0x6c, 0x64, 0x61, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x64,
	0x61, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x64, 0x61, 0x70,
	0x42, 0x08, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xd5, 0x03, 0x0a, 0x0a, 0x4f,
	0x69, 0x64, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x2a, 0x0a,
	0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x53, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0d, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x72, 0x6c, 0x88,
	0x01, 0x01, 0x12, 0x1e, 0x0a, 0x08, 0x6a, 0x77, 0x6b, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x07, 0x6a, 0x77, 0x6b, 0x73, 0x55, 0x72, 0x6c, 0x88,
	0x01, 0x01, 0x12, 0x32, 0x0a, 0x12, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x48, 0x03,
	0x52, 0x11, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x04, 0x52, 0x09, 0x6c, 0x6f,
	0x67, 0x6f, 0x75, 0x74, 0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x42, 0x10, 0x0a,
	0x0e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x42,
	0x0b, 0x0a, 0x09, 0x5f, 0x6a, 0x77, 0x6b, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x42, 0x15, 0x0a, 0x13,
	0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x5f, 0x75,
	0x72, 0x6c, 0x22, 0xa3, 0x05, 0x0a, 0x0a, 0x4c, 0x64, 0x61, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x64,
	0x5f, 0x64, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x64, 0x44,
	0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x62, 0x69, 0x6e, 0x64, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x69, 0x6e, 0x64,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x5f, 0x64, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x44, 0x6e, 0x12, 0x3b, 0x0a, 0x17, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x5f, 0x6c, 0x64, 0x61, 0x70, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x15, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x4c, 0x64, 0x61, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x31, 0x0a, 0x12, 0x72, 0x64, 0x6e, 0x5f, 0x6c, 0x64, 0x61, 0x70, 0x5f, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x10, 0x72, 0x64, 0x6e, 0x4c, 0x64, 0x61, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x13, 0x75, 0x75, 0x69, 0x64, 0x5f, 0x6c, 0x64,
	0x61, 0x70, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x02, 0x52, 0x11, 0x75, 0x75, 0x69, 0x64, 0x4c, 0x64, 0x61, 0x70, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x13, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x11, 0x75, 0x73, 0x65, 0x72, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x20, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x04, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x1b, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x05, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x31,
	0x0a, 0x12, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x5f, 0x73, 0x70, 0x69, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x48, 0x06, 0x52, 0x10, 0x75, 0x73,
	0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x70, 0x69, 0x88, 0x01,
	0x01, 0x12, 0x23, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x08, 0x48, 0x07, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x1a, 0x0a, 0x18, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x5f, 0x6c, 0x64, 0x61, 0x70, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x72, 0x64, 0x6e, 0x5f, 0x6c, 0x64, 0x61, 0x70, 0x5f,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x5f, 0x6c, 0x64, 0x61, 0x70, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61, 0x75,
	0x74, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x76, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x70, 0x69, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xbc, 0x01, 0x0a, 0x16, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4a, 0x0a, 0x0a, 0x63,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xe9, 0x01, 0x0a, 0x19, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4c, 0x0a, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x12, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0xc9, 0x01, 0x0a, 0x16, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x45,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x3d, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x65, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a,
	0xab, 0x01, 0x0a, 0x15, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x23, 0x49, 0x44, 0x45,
	0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x50,
	0x48, 0x41, 0x53, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x50,
	0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x50, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x10, 0x01, 0x12, 0x21, 0x0a, 0x1d, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54,
	0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x50, 0x48, 0x41, 0x53, 0x45,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x23, 0x0a, 0x1f, 0x49, 0x44, 0x45, 0x4e,
	0x54, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x50, 0x48,
	0x41, 0x53, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x2a, 0xd8, 0x01,
	0x0a, 0x1c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2f,
	0x0a, 0x2b, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49,
	0x44, 0x45, 0x52, 0x5f, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x2b, 0x0a, 0x27, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56,
	0x49, 0x44, 0x45, 0x52, 0x5f, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x59, 0x10, 0x01, 0x12, 0x2d, 0x0a, 0x29,
	0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45,
	0x52, 0x5f, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x55, 0x4e, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x59, 0x10, 0x02, 0x12, 0x2b, 0x0a, 0x27, 0x49,
	0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52,
	0x5f, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x42, 0xde, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x42, 0x19, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50,
	0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var file_osac_private_v1_identity_provider_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_osac_private_v1_identity_provider_type_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_osac_private_v1_identity_provider_type_proto_goTypes = []any{
	(IdentityProviderPhase)(0),        // 0: osac.private.v1.IdentityProviderPhase
	(IdentityProviderHealthStatus)(0), // 1: osac.private.v1.IdentityProviderHealthStatus
	(*IdentityProvider)(nil),          // 2: osac.private.v1.IdentityProvider
	(*IdentityProviderSpec)(nil),      // 3: osac.private.v1.IdentityProviderSpec
	(*OidcConfig)(nil),                // 4: osac.private.v1.OidcConfig
	(*LdapConfig)(nil),                // 5: osac.private.v1.LdapConfig
	(*IdentityProviderStatus)(nil),    // 6: osac.private.v1.IdentityProviderStatus
	(*IdentityProviderCondition)(nil), // 7: osac.private.v1.IdentityProviderCondition
	(*IdentityProviderHealth)(nil),    // 8: osac.private.v1.IdentityProviderHealth
	(*Metadata)(nil),                  // 9: osac.private.v1.Metadata
	(ConditionStatus)(0),              // 10: osac.private.v1.ConditionStatus
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_osac_private_v1_identity_provider_type_proto_depIdxs = []int32{
	9,  // 0: osac.private.v1.IdentityProvider.metadata:type_name -> osac.private.v1.Metadata
	3,  // 1: osac.private.v1.IdentityProvider.spec:type_name -> osac.private.v1.IdentityProviderSpec
	6,  // 2: osac.private.v1.IdentityProvider.status:type_name -> osac.private.v1.IdentityProviderStatus
	4,  // 3: osac.private.v1.IdentityProviderSpec.oidc:type_name -> osac.private.v1.OidcConfig
	5,  // 4: osac.private.v1.IdentityProviderSpec.ldap:type_name -> osac.private.v1.LdapConfig
	0,  // 5: osac.private.v1.IdentityProviderStatus.phase:type_name -> osac.private.v1.IdentityProviderPhase
	7,  // 6: osac.private.v1.IdentityProviderStatus.conditions:type_name -> osac.private.v1.IdentityProviderCondition
	10, // 7: osac.private.v1.IdentityProviderCondition.status:type_name -> osac.private.v1.ConditionStatus
	11, // 8: osac.private.v1.IdentityProviderCondition.last_transition_time:type_name -> google.protobuf.Timestamp
	1,  // 9: osac.private.v1.IdentityProviderHealth.status:type_name -> osac.private.v1.IdentityProviderHealthStatus
	11, // 10: osac.private.v1.IdentityProviderHealth.last_checked:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_osac_private_v1_identity_provider_type_proto_init() }
func file_osac_private_v1_identity_provider_type_proto_init() {
	if File_osac_private_v1_identity_provider_type_proto != nil {
		return
	}
	file_osac_private_v1_condition_status_type_proto_init()
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_identity_provider_type_proto_msgTypes[1].OneofWrappers = []any{
		(*identityProviderSpec_Oidc)(nil),
		(*identityProviderSpec_Ldap)(nil),
	}
	file_osac_private_v1_identity_provider_type_proto_msgTypes[2].OneofWrappers = []any{}
	file_osac_private_v1_identity_provider_type_proto_msgTypes[3].OneofWrappers = []any{}
	file_osac_private_v1_identity_provider_type_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_identity_provider_type_proto_rawDesc), len(file_osac_private_v1_identity_provider_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_identity_provider_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_identity_provider_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_identity_provider_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_identity_provider_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_identity_provider_type_proto = out.File
	file_osac_private_v1_identity_provider_type_proto_goTypes = nil
	file_osac_private_v1_identity_provider_type_proto_depIdxs = nil
}
