//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/public_ip_attachments_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublicIPAttachments_List_FullMethodName   = "/osac.private.v1.PublicIPAttachments/List"
	PublicIPAttachments_Get_FullMethodName    = "/osac.private.v1.PublicIPAttachments/Get"
	PublicIPAttachments_Create_FullMethodName = "/osac.private.v1.PublicIPAttachments/Create"
	PublicIPAttachments_Update_FullMethodName = "/osac.private.v1.PublicIPAttachments/Update"
	PublicIPAttachments_Delete_FullMethodName = "/osac.private.v1.PublicIPAttachments/Delete"
	PublicIPAttachments_Signal_FullMethodName = "/osac.private.v1.PublicIPAttachments/Signal"
)

// PublicIPAttachmentsClient is the client API for PublicIPAttachments service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicIPAttachmentsClient interface {
	// Retrieves the list of public IP attachments.
	List(ctx context.Context, in *PublicIPAttachmentsListRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsListResponse, error)
	// Retrieves the details of one specific public IP attachment.
	Get(ctx context.Context, in *PublicIPAttachmentsGetRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsGetResponse, error)
	// Creates a new public IP attachment. Binds a PublicIP to a target resource.
	Create(ctx context.Context, in *PublicIPAttachmentsCreateRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsCreateResponse, error)
	// Updates an existing public IP attachment. Only metadata (labels, annotations) can be changed.
	Update(ctx context.Context, in *PublicIPAttachmentsUpdateRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsUpdateResponse, error)
	// Deletes a public IP attachment. Triggers the detach workflow to unbind the PublicIP from the target.
	Delete(ctx context.Context, in *PublicIPAttachmentsDeleteRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *PublicIPAttachmentsSignalRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsSignalResponse, error)
}

type publicIPAttachmentsClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicIPAttachmentsClient(cc grpc.ClientConnInterface) PublicIPAttachmentsClient {
	return &publicIPAttachmentsClient{cc}
}

func (c *publicIPAttachmentsClient) List(ctx context.Context, in *PublicIPAttachmentsListRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPAttachmentsListResponse)
	err := c.cc.Invoke(ctx, PublicIPAttachments_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPAttachmentsClient) Get(ctx context.Context, in *PublicIPAttachmentsGetRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPAttachmentsGetResponse)
	err := c.cc.Invoke(ctx, PublicIPAttachments_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPAttachmentsClient) Create(ctx context.Context, in *PublicIPAttachmentsCreateRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPAttachmentsCreateResponse)
	err := c.cc.Invoke(ctx, PublicIPAttachments_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPAttachmentsClient) Update(ctx context.Context, in *PublicIPAttachmentsUpdateRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPAttachmentsUpdateResponse)
	err := c.cc.Invoke(ctx, PublicIPAttachments_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPAttachmentsClient) Delete(ctx context.Context, in *PublicIPAttachmentsDeleteRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPAttachmentsDeleteResponse)
	err := c.cc.Invoke(ctx, PublicIPAttachments_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPAttachmentsClient) Signal(ctx context.Context, in *PublicIPAttachmentsSignalRequest, opts ...grpc.CallOption) (*PublicIPAttachmentsSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPAttachmentsSignalResponse)
	err := c.cc.Invoke(ctx, PublicIPAttachments_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicIPAttachmentsServer is the server API for PublicIPAttachments service.
// All implementations must embed UnimplementedPublicIPAttachmentsServer
// for forward compatibility.
type PublicIPAttachmentsServer interface {
	// Retrieves the list of public IP attachments.
	List(context.Context, *PublicIPAttachmentsListRequest) (*PublicIPAttachmentsListResponse, error)
	// Retrieves the details of one specific public IP attachment.
	Get(context.Context, *PublicIPAttachmentsGetRequest) (*PublicIPAttachmentsGetResponse, error)
	// Creates a new public IP attachment. Binds a PublicIP to a target resource.
	Create(context.Context, *PublicIPAttachmentsCreateRequest) (*PublicIPAttachmentsCreateResponse, error)
	// Updates an existing public IP attachment. Only metadata (labels, annotations) can be changed.
	Update(context.Context, *PublicIPAttachmentsUpdateRequest) (*PublicIPAttachmentsUpdateResponse, error)
	// Deletes a public IP attachment. Triggers the detach workflow to unbind the PublicIP from the target.
	Delete(context.Context, *PublicIPAttachmentsDeleteRequest) (*PublicIPAttachmentsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *PublicIPAttachmentsSignalRequest) (*PublicIPAttachmentsSignalResponse, error)
	mustEmbedUnimplementedPublicIPAttachmentsServer()
}

// UnimplementedPublicIPAttachmentsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicIPAttachmentsServer struct{}

func (UnimplementedPublicIPAttachmentsServer) List(context.Context, *PublicIPAttachmentsListRequest) (*PublicIPAttachmentsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPublicIPAttachmentsServer) Get(context.Context, *PublicIPAttachmentsGetRequest) (*PublicIPAttachmentsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPublicIPAttachmentsServer) Create(context.Context, *PublicIPAttachmentsCreateRequest) (*PublicIPAttachmentsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPublicIPAttachmentsServer) Update(context.Context, *PublicIPAttachmentsUpdateRequest) (*PublicIPAttachmentsUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPublicIPAttachmentsServer) Delete(context.Context, *PublicIPAttachmentsDeleteRequest) (*PublicIPAttachmentsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPublicIPAttachmentsServer) Signal(context.Context, *PublicIPAttachmentsSignalRequest) (*PublicIPAttachmentsSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedPublicIPAttachmentsServer) mustEmbedUnimplementedPublicIPAttachmentsServer() {}
func (UnimplementedPublicIPAttachmentsServer) testEmbeddedByValue()                             {}

// UnsafePublicIPAttachmentsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicIPAttachmentsServer will
// result in compilation errors.
type UnsafePublicIPAttachmentsServer interface {
	mustEmbedUnimplementedPublicIPAttachmentsServer()
}

func RegisterPublicIPAttachmentsServer(s grpc.ServiceRegistrar, srv PublicIPAttachmentsServer) {
	// If the following call pancis, it indicates UnimplementedPublicIPAttachmentsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublicIPAttachments_ServiceDesc, srv)
}

func _PublicIPAttachments_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPAttachmentsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPAttachmentsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPAttachments_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPAttachmentsServer).List(ctx, req.(*PublicIPAttachmentsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPAttachments_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPAttachmentsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPAttachmentsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPAttachments_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPAttachmentsServer).Get(ctx, req.(*PublicIPAttachmentsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPAttachments_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPAttachmentsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPAttachmentsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPAttachments_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPAttachmentsServer).Create(ctx, req.(*PublicIPAttachmentsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPAttachments_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPAttachmentsUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPAttachmentsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPAttachments_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPAttachmentsServer).Update(ctx, req.(*PublicIPAttachmentsUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPAttachments_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPAttachmentsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPAttachmentsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPAttachments_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPAttachmentsServer).Delete(ctx, req.(*PublicIPAttachmentsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPAttachments_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPAttachmentsSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPAttachmentsServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPAttachments_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPAttachmentsServer).Signal(ctx, req.(*PublicIPAttachmentsSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicIPAttachments_ServiceDesc is the grpc.ServiceDesc for PublicIPAttachments service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicIPAttachments_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.PublicIPAttachments",
	HandlerType: (*PublicIPAttachmentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _PublicIPAttachments_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PublicIPAttachments_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PublicIPAttachments_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PublicIPAttachments_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PublicIPAttachments_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _PublicIPAttachments_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/public_ip_attachments_service.proto",
}
