name: pre-commit

on:
  pull_request:
    paths-ignore:
      - 'OWNERS'
      - 'LICENSE'
      - '*.md'
      - 'docs/**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
    - uses: actions/setup-python@v7
      with:
        python-version: "3.13"
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: -c .pre-commit-config-ci.yaml

  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@v7
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.1
